In [3]:
import torch

tensor = torch.ones(2, 3)
"""
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
"""
tensor[:,1] = 0
print(tensor)



tensor([[1., 0., 1.],
        [1., 0., 1.]])


两种矩阵乘法

In [5]:
y1 = tensor@tensor.T # 矩阵乘法
print(y1)
z1 = tensor*tensor #对应位置元素相乘
print(z1)

tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 0., 1.],
        [1., 0., 1.]])


In [7]:
x = torch.randn(3, 4)
v = x.view(2, 6)
r = x.reshape(2, 6)
print(x)
print(v)
print(r)

tensor([[-1.1128,  0.1995,  0.6658, -1.8890],
        [-0.1050,  0.0226,  0.8165,  1.8140],
        [ 0.5787,  1.5449,  0.5560,  0.6404]])
tensor([[-1.1128,  0.1995,  0.6658, -1.8890, -0.1050,  0.0226],
        [ 0.8165,  1.8140,  0.5787,  1.5449,  0.5560,  0.6404]])
tensor([[-1.1128,  0.1995,  0.6658, -1.8890, -0.1050,  0.0226],
        [ 0.8165,  1.8140,  0.5787,  1.5449,  0.5560,  0.6404]])


In [8]:
v[0, 0] = 999
print(x)

tensor([[ 9.9900e+02,  1.9948e-01,  6.6580e-01, -1.8890e+00],
        [-1.0500e-01,  2.2626e-02,  8.1646e-01,  1.8140e+00],
        [ 5.7870e-01,  1.5449e+00,  5.5598e-01,  6.4037e-01]])


view() 遇到不连续，会直接报错！
v = x_t.view(2, 6)  # 运行这行会报错: RuntimeError<br>
但是reshape在内存不连续的时候可以复制一份，克服内存不连续的问题
还可以直接view(-1)将矩阵转换为一维向量，方便查看

In [11]:
x = torch.randn(3, 4)
x_t = x.t()  # 转置操作后，内存变得不连续
print(f"x_t 是否连续: {x_t.is_contiguous()}")  # False
# reshape() 遇到不连续，不会报错，它会自动复制一份新内存来处理
r = x_t.reshape(2, 6)

x_t 是否连续: False


广播机制实现了时两个或两个以上数组的运算，即使这些数组的shape不是完全相同的，只需要满足如下任意一个条件即可。

如果两个数组的后缘维度（trailing dimension，即从末尾开始算起的维度）的轴长度相符，
或

如果两个数组的后缘维度（trailing dimension，即从末尾开始算起的维度）的轴长度其中的一方的长度为1。
————————————————
版权声明：本文为CSDN博主「u013250861」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/u013250861/article/details/123416628